backend:
  name: git-gateway
  repo: jack970/prosaude
  branch: main
  commit_messages:
    create: 'Post Criado {{collection}} “{{slug}}”'
    update: 'Post Atualizado {{collection}} “{{slug}}”'
    delete: 'Post Deletado {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

local_backend: true

display_url: https://prosaude.netlify.app
logo_url: https://prosaude.netlify.app/icons/icon-192x192.png
site_url: https://prosaude.netlify.app

publish_mode: editorial_workflow

media_folder: static/assets/img
public_folder: assets/img
locale: 'pt'

collections:
  - name: posts # Used in routes, e.g. /admin/collections/blog
    label: Posts # Used in the UI
    folder: posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template i.e. title.md
    fields:
    - {label: "Título", name: "title", widget: "string"}
    - {label: "Descrição", name: "description", widget: "string"}
    - {label: "Tags", name: "tags", widget: "list", default: ["Notícias"], max: 3, min: 1}
    - {label: "Data", name: "date", widget: "datetime", format: 'YYYY-MM-DD hh:mm:ss'}
    - name: pdf
      label: "PDF"
      widget: list
      fields:
        - { label: "Titulo PDF", name: "alt", widget: "string" }
        - { label: "Arquivo PDF", name: "url", widget: "file" }
    - {label: "Imagem da Notícia", name: "thumbnail", widget: "image"}
    - {label: "Corpo", name: "body", widget: "markdown"}