backend:
  name: github
  repo: jack970/prosaude
  branch: master

publish_mode: editorial_workflow

media_folder: static/assets/img
public_folder: assets/img

collections:
  - name: posts # Used in routes, e.g. /admin/collections/blog
    label: Posts # Used in the UI
    folder: posts # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}' # Filename template i.e. title.md
    fields: # The fields for each document, usually in front matter
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'posts' }
      - {
          label: 'Data',
          name: 'date',
          widget: 'datetime',
          format: 'YYYY-MM-DD hh:mm:ss',
        }
      - { label: 'Imagem da Notícia', name: 'image', widget: 'image' }
      - { label: 'Título', name: 'title', widget: 'string' }
      - { label: 'Descrição', name: 'description', widget: 'string' }
      - { label: 'Conteúdo da Notícia', name: 'body', widget: 'markdown' }